name: Auto Reply to Issues

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Add a Comment
        uses: actions-ecosystem/action-add-comment@v1
        with:
          github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          comment: |
            Thank you for opening this issue! 🎉  
            Our team will review it soon. In the meantime, check the [contribution guidelines](CONTRIBUTING.md) for more details.  
